ARGV = []
TRUE = true
FALSE = false
STDOUT = IO.new
STDIN = IO.new
STDERR = IO.new
ENV = {}
NIL = nil
RUBY_PATCHLEVEL = 273
RUBY_COPYRIGHT = 'ruby - Copyright (C) 1993-2014 Yukihiro Matsumoto'
TOPLEVEL_BINDING = Binding.new
RUBY_VERSION = '2.1.5'
RUBY_PLATFORM = 'i386-mingw32'
