// Generated by CoffeeScript 1.8.0
(function() {
  var item, type, _i, _len;

  type = ["rice", "crab", "cuke"];

  for (_i = 0, _len = type.length; _i < _len; _i++) {
    item = type[_i];
    if (item !== "rice") {
      alert(item);
    }
  }

}).call(this);
